#!/bin/bash

branches=$(./get-branches)
dpg_branch=$(echo "$branches" | awk 'NR==1')
original_branch=$(echo "$branches" | awk 'NR==2')

correct_setup_msg="Doppelganger branch of $original_branch is correctly set up!"

if [ $(git rev-parse $dpg_branch) == $(git rev-parse $original_branch) ]; then
	echo "$correct_setup_msg (did not diverge yet)"
elif git diff --quiet $dpg_branch $original_branch; then 
	echo "$correct_setup_msg (diverged)"
else
	echo "ERROR: Doppelganger branch of $original_branch has different working tree!" >&2
	exit 1
fi

