#!/bin/bash

original_branch=$(./get-original)

old_dpg_commit=$(git rev-parse HEAD)

git commit

new_dpg_commit=$(git rev-parse HEAD)

# Get the commit message
# The first line of git rev-list contains the commit hash, so we drop it with sed
message=$(git rev-list --format=%B --max-count=1 $new_dpg_commit | sed "1d")

./update-original -m $message $original_branch $old_dpg_commit $new_dpg_commit

