#!/bin/bash

original_branch=$(./get-original)

old_dpg_commit=$(git rev-parse HEAD)

git commit --amend

new_dpg_commit=$(git rev-parse HEAD)

./update-original $original_branch $old_dpg_commit $new_dpg_commit

