#!/bin/bash

commands_dir=$(dirname $0)/git-dpg-commands

command=$1

if [ -z "$command" ]; then
    >&2 echo "Error: No doppelganger command provided"
    exit 1
fi

if [ -f "$commands_dir/$command" ]; then
    $commands_dir/$command "${@:2}"  # pass other arguments to the command
    exit 0
else
    >&2 echo "Error: Doppelganger command "$command" does not exist"
    exit 1
fi

