#!/bin/bash

# Git reference-transaction hooks are required to run Git Doppelganger
required_git_version="2.28"
installed_git_version=$(git --version | sed 's/git version //')

if [[ 
    $(
        echo -e "$required_git_version\n$installed_git_version" | sort --version-sort | head -n 1
    ) != $required_git_version
]]; then
    >&2 echo "Error: Could not install Git Doppelganger."
    >&2 echo "Required Git version: $required_git_version"
    >&2 echo "Installed Git version: $installed_git_version"
    exit 1
fi

src_dir=$(dirname $0)
dst_dir="$HOME/.local/bin"
cp $src_dir/git-dpg $dst_dir
cp -r $src_dir/git-dpg-commands $dst_dir
cp -r $src_dir/git-dpg-hooks $dst_dir

