#!/bin/bash

./check

branches=$(./get-branches)
dpg_branch=$(echo "$branches" | awk 'NR==1')
original_branch=$(echo "$branches" | awk 'NR==2')

git rebase $1

git commit --amend

# Ref: https://stackoverflow.com/a/17324759
git switch -c $dpg_branch.tmp
git reset --soft $original_branch
git switch $original_branch
git branch -d $dpg_branch.tmp
git commit
git switch $dpg_branch
git merge $original_branch

