#!/bin/bash

# Get the name of the instruction file
instruction_file=$1

# Open the instruction file in the default text editor and let the user edit it
$(git config --global core.editor) $instruction_file

if grep -Ev '^\s*(#|$)' $instruction_file > /dev/null; then
	# Instructions file does not contain only comments or empty lines and is therefore valid
	# Add a command to run the post-rebase script at the end of the rebase
	echo "exec /Users/nd/git-projects/doppelganger/post-rebase" >> $instruction_file
fi

