#!/bin/bash

rebasing_commit=$(git rev-parse $1)

original_branch=$(./get-original)
old_dpg_commit=$(git rev-parse HEAD)

export GIT_SEQUENCE_EDITOR="./rebase-editor $original_branch $old_dpg_commit $rebasing_commit"

git rebase --interactive $rebasing_commit

