#!/bin/bash

set -eu

tracked_stash=$1
untracked_stash=$2

{
    git checkout - --

    if [ "$untracked_stash" = 1 ]; then
        git stash pop
    fi

    if [ "$tracked_stash" = 1 ]; then
        git stash pop
    fi
} > /dev/null

